font_family JetBrainsMono NF
font_size 22 

background_opacity 0.8
background_blur 30

hide_window_decorations titlebar-only

text_composition_strategy legacy
#--------------------------------------------------------------------
# Key bindings
#--------------------------------------------------------------------
# Clipboard
map super+v             paste_from_clipboard
map super+c             copy_or_interrupt

# Screen
map super+k combine : clear_terminal scroll active : send_text normal,application \x0c

# Miscellaneous
map super+equal      increase_font_size
map super+minus    decrease_font_size
map super+0 restore_font_size

# Scrolling
map super+shift+g       show_last_command_output
map super+ctrl+p        scroll_to_prompt -1
map super+ctrl+n        scroll_to_prompt 1

#--------------------------------------------------------------------
# Theme
#--------------------------------------------------------------------
# Monokai

background #272822
foreground #f8f8f2
cursor #f8f8f2
selection_background #f8f8f2
selection_foreground #272822
active_tab_background #75715e
active_tab_foreground #272822
active_border_color #75715e
inactive_tab_background #272822
inactive_tab_foreground #75715e
inactive_border_color #75715e
url_color #f8f8f2

# 16 Color Space

# black
color0 #272822
color8 #75715e
# red
color1 #f92672
color9 #f92672
# green
color2 #a6e22e
color10 #a6e22e
# yellow
color3 #e6db74
color11 #e6db74
# blue
color4 #66d9ef
color12 #66d9ef
# magenta
color5 #fd971f
color13 #fd971f
# cyan
color6 #ae81ff
color14 #ae81ff
# white
color7 #f8f8f2
color15 #f8f8f2# blue
color4  #61afef
color12 #61afef

# magenta
color5   #c678dd
color13  #c678dd

# cyan
color6   #56b6c2
color14  #56b6c2

# white
color7   #dcdfe4
color15  #dcdfe4
